---
parser: babel-eslint

extends: eslint-config-shakacode

plugins:
  - react

globals:
  __DEBUG_SERVER_ERRORS__: true
  __SERVER_ERRORS__: true

env:
  browser: true
  node: true
  mocha: true

rules:
  import/extensions: [2, { js: "never", jsx: "never" }]

  # Good idea, but let's go to flow before fixing all these
  react/forbid-prop-types: 0

#  arrow-parens:
#    - 0
#    - "as-needed"

settings:
  import/resolver:
    webpack:
      config: 'webpack.client.config.js'
